server:
  port: 8181
spring:
  application:
    name: client-service

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.uuid}
#        health-check-path: "/actuator/health"

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - mappings
          - metrics