spring:
  application:
    name: gateway2-service

  cloud:
    consul:
      host: localhost
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.uuid}

    gateway:
      routes:
        - id: to-client
          uri: lb://client-service
          predicates:
            - Path=/client/**
            - Method=GET,POST
          filters:
            - RewritePath=/client/(?<path>.*),/$\{path}
            - AddRequestParameter=my-param,its-value
            - Retry=3
        - id: to-movie
          uri: lb://movie-service
          predicates:
            - Path=/movie/**
          filters:
            - RewritePath=/movie/(?<path>.*),/$\{path}
        - id: word
          uri: lb://movie-service
          predicates:
            - Path=/word
          filters:
            - AddRequestParameter=word,gateway
      discovery:
        locator:
          enabled: true