spring:
  application:
    name: gateway2-service

  cloud:
    consul:
      host: localhost
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.uuid}

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: to-client
          uri: lb://client-service
          predicates:
            - Path=/client/**
            - Method=GET,POST
          filters:
            - RewritePath=/client/(?<path>.*),/$\{path}
            - AddRequestParameter=my-param,its-value
            - Retry=3
        - id: to-movie
          uri: lb://movie-service
          predicates:
            - Path=/movie/**
          filters:
            - RewritePath=/movie/(?<path>.*),/$\{path}
        - id: word
          uri: lb://movie-service
          predicates:
            - Path=/word
            - name: NumberOfParams
              args:
                equals: 0
#                min: 0
#                max: 0
          filters:
            - name: AddRequestParameter
              args:
                name: word
                value: gateway
            - name: Logger

